In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix
import pandas as pd

In [2]:
from mnist import MNIST
data = MNIST(data_dir="data/MNIST/")

##### All of these data.x_train, data.x_test, data.x_val are numpy array.

In [3]:
print(data.x_train.shape)
print(data.y_train.shape)
print(data.x_test.shape)
print(data.y_test.shape)
print(data.x_val.shape)
print(data.y_val.shape)
print(data.y_train_cls[0:5])
print(data.y_train[0:5])
print(data.y_test_cls[0:5])
print(data.y_test[0:5])
print(data.y_val_cls[0:5])
print(data.y_val[0:5])

(55000, 784)
(55000, 10)
(10000, 784)
(10000, 10)
(5000, 784)
(5000, 10)
[5 0 4 1 9]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[7 2 1 0 4]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[1 2 8 7 4]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [6]:
>>> from sklearn.linear_model import LogisticRegression

# saga stands for "Stochastic Average Gradient descent solver".

>>> clf = LogisticRegression(random_state=0, solver='saga',
...                          multi_class='multinomial').fit(data.x_train, data.y_train_cls)

C:\Users\heman\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [7]:
clf.predict(data.x_test[:5, :])

array([7, 2, 1, 0, 4])

In [8]:
>>> clf.predict_proba(data.x_test[:2, :])

array([[5.51061715e-07, 2.71686350e-13, 2.29016909e-06, 3.20958675e-03,
        8.11532647e-08, 1.01511321e-05, 8.64744330e-12, 9.96538291e-01,
        6.22564144e-06, 2.32823142e-04],
       [6.08095629e-05, 1.05659981e-06, 9.95955759e-01, 5.16229728e-04,
        2.75074425e-16, 2.03590141e-03, 1.33288180e-03, 6.59714672e-20,
        9.73619084e-05, 6.20134956e-15]])

In [10]:
clf.score(data.x_test, data.y_test_cls)

0.9258